name = "laGP"
uuid = "895baa0a-b668-4fc8-b1fe-ed27223c4cb2"
version = "0.1.0"
authors = ["Joshua Leon"]

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractGPs = "0.5"
CairoMakie = "0.12, 0.13"
ChainRulesCore = "1"
Distances = "0.10"
Distributions = "0.25.123"
JSON3 = "1"
KernelFunctions = "0.10"
LatinHypercubeSampling = "1"
NearestNeighbors = "0.4"
Optim = "1"
PDMats = "0.11"
SpecialFunctions = "2"
Zygote = "0.6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
