name = "laGP"
uuid = "895baa0a-b668-4fc8-b1fe-ed27223c4cb2"
version = "0.1.0"
authors = ["Joshua Leon"]

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbstractGPs = "0.5"
CairoMakie = "0.15.8"
Distributions = "0.25.123"
KernelFunctions = "0.10"
LatinHypercubeSampling = "1.9.0"
Optim = "1"
SpecialFunctions = "2"
julia = "1.10"

[extras]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JSON3", "Test"]
